# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AppointmentsGetSlotsGet200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AppointmentsGetSlotsGet200Response - a model defined in OpenAPI

        slots: The slots of this AppointmentsGetSlotsGet200Response [Optional].
    """

    slots: Optional[List[str]] = Field(alias="slots", default=None)

AppointmentsGetSlotsGet200Response.update_forward_refs()
