steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/chatgpt-report-framework", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/chatgpt-report-framework"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "chatgpt-report-framework",
        "--image",
        "gcr.io/$PROJECT_ID/chatgpt-report-framework",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]
