# coding: utf-8

"""
    SummaryGenerator-OpenAPI

    SummaryGenerator-Service

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""
import sys

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from openapi_server.apis.patients import router as CreateCareplanApiRouter
# app = FastAPI()
from fastapi import APIRouter, Depends
from openapi_server.authentication_strategy import AuthenticationStrategy
app = FastAPI(
    title="Patients data service",
    description="Data Service",
    version="0.0.1",
    docs_url="/docs",
    redoc_url=None,
    openapi_url="/docs/swagger.json",
)
# # Configure CORS
auth_strategy = AuthenticationStrategy()

# Add the authentication middleware to the FastAPI app
# app.add_middleware()

# app.add_middleware()

app.add_middleware(

    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    
    
)
# router = APIRouter()
# @router.get("/secure_route")
# async def secure_route_handler(user_data: dict = Depends(auth_strategy)):
#     # Your secure route logic here
#     return {"message": "This route requires authentication."}



# app.include_router(router)
app.include_router(CreateCareplanApiRouter,dependencies=[Depends(auth_strategy)])




