# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ColumnDto(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ColumnDto - a model defined in OpenAPI

        column_name: The column_name of this ColumnDto [Optional].
        label: The label of this ColumnDto [Optional].
    """

    column_name: Optional[str] = Field(alias="columnName", default=None)
    label: Optional[str] = Field(alias="label", default=None)

ColumnDto.update_forward_refs()
