# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class CreateYAxisDto(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateYAxisDto - a model defined in OpenAPI

        column_name: The column_name of this CreateYAxisDto [Optional].
        label: The label of this CreateYAxisDto [Optional].
        axis_border_color: The axis_border_color of this CreateYAxisDto [Optional].
        axis_text_color: The axis_text_color of this CreateYAxisDto [Optional].
    """

    column_name: Optional[str] = Field(alias="columnName", default=None)
    label: Optional[str] = Field(alias="label", default=None)
    axis_border_color: Optional[str] = Field(alias="axisBorderColor", default=None)
    axis_text_color: Optional[str] = Field(alias="axisTextColor", default=None)

CreateYAxisDto.update_forward_refs()
