# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Messages(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Messages - a model defined in OpenAPI

        role: The role of this Messages [Optional].
        content: The content of this Messages [Optional].
    """

    role: Optional[str] = Field(alias="role", default=None)
    content: Optional[str] = Field(alias="content", default=None)

Messages.update_forward_refs()
