# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class NotesInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NotesInner - a model defined in OpenAPI

        noteid: The noteid of this NotesInner.
        notetype: The notetype of this NotesInner [Optional].
        date: The date of this NotesInner [Optional].
        condition: The condition of this NotesInner [Optional].
        addedby: The addedby of this NotesInner [Optional].
        notes: The notes of this NotesInner [Optional].
    """

    noteid: str = Field(alias="noteid")
    notetype: Optional[str] = Field(alias="notetype", default=None)
    date: Optional[str] = Field(alias="date", default=None)
    condition: Optional[str] = Field(alias="condition", default=None)
    addedby: Optional[str] = Field(alias="addedby", default=None)
    notes: Optional[str] = Field(alias="notes", default=None)

NotesInner.update_forward_refs()
