# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class PreauthorizationDto(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PreauthorizationDto - a model defined in OpenAPI

        id: The id of this PreauthorizationDto [Optional].
        appointment_type: The appointment_type of this PreauthorizationDto [Optional].
        appointment_status: The appointment_status of this PreauthorizationDto [Optional].
        appointment_date: The appointment_date of this PreauthorizationDto [Optional].
    """

    # id: Optional[str] = Field(alias="id", default=None)
    # appointment_type: Optional[int] = Field(alias="appointmentType", default=None)
    # appointment_status: Optional[bool] = Field(alias="appointmentStatus", default=None)
    # appointment_date: Optional[date] = Field(alias="appointmentDate", default=None)
    role: Optional[str] = Field(alias="role", default=None)
    content: Optional[str] = Field(alias="content", default=None)

PreauthorizationDto.update_forward_refs()
