# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Reviewlabpromt(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Reviewlabpromt - a model defined in OpenAPI

        promt: The promt of this Reviewlabpromt [Optional].
    """

    promt: Optional[str] = Field(alias="promt", default=None)

Reviewlabpromt.update_forward_refs()
