# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.messages import Messages


class TextScheduleAppointments(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TextScheduleAppointments - a model defined in OpenAPI

        text: The text of this TextScheduleAppointments.
        patient_id: The patient_id of this TextScheduleAppointments [Optional].
        doctor_id: The doctor_id of this TextScheduleAppointments [Optional].
    """

    text: List[Messages] = Field(alias="text")

TextScheduleAppointments.update_forward_refs()
