# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.messages import Messages

class TranscriptionDto(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConversationInner - a model defined in OpenAPI

        doctor: The doctor of this ConversationInner [Optional].
        patient: The patient of this ConversationInner [Optional].
    """

    doctor: Optional[str] = Field(alias="Doctor", default=None)
    patient: Optional[str] = Field(alias="Patient", default=None)
    # text: List[Messages] = Field(alias="text")
    # role: Optional[str] = Field(alias="role", default=None)
    # content: Optional[str] = Field(alias="content", default=None)



TranscriptionDto.update_forward_refs()