# coding: utf-8

"""
    Appointments OpenAPI

    Appointments Service

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.appointments_api import router as AppointmentsApiRouter

app = FastAPI(
    title="Appointments OpenAPI",
    description="Appointments Service",
    version="0.0.1",
)

app.include_router(AppointmentsApiRouter)
